[Settings]
  ID = "ac334778-789c-4880-8384-234d50c1a7de"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[build]
  command = "yarn build"

[functions]
  node_bundler = "esbuild"